In [1]:
%load_ext  watermark

%watermark -v -m -p numpy -g

CPython 3.5.2
IPython 5.3.0

numpy 1.12.0

compiler   : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
system     : Linux
release    : 4.4.57-boot2docker
machine    : x86_64
processor  : 
CPU cores  : 4
interpreter: 64bit
Git hash   : 3f907ca62ed880bf188f09fedd1afd4b4af8134e


In [2]:
import numpy as np

In [3]:
np.show_config()

blis_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    language = c
    library_dirs = ['/opt/conda/lib']
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
lapack_opt_info:
    language = c
    library_dirs = ['/opt/conda/lib']
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]
openblas_info:
    language = c
    library_dirs = ['/opt/conda/lib']
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]
openblas_lapack_info:
    language = c
    library_dirs = ['/opt/conda/lib']
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]


# Matrix Multiplication

##  (ijk, ikj, jik, jki, kij, kji) 

kij  3: 36.6 µs per loop  
ikj  3: 37 µs per loop  

kji  3: 38.1 µs per loop  
jki  3: 38.7 µs per loop  
ijk  3: 41 µs per loop  
jik  3: 41.3 µs per loop  

In [89]:
A = np.arange(6).reshape(3,2)
B = np.arange(8).reshape(2,4)
C = A.dot(B)

C

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [90]:
%timeit A.dot(B)

The slowest run took 144.91 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 975 ns per loop


In [5]:
from gvpy.matmat import matmat_ijk
from gvpy.matmat import matmat_ikj


In [14]:
%timeit matmat_ijk(A,B)

10000 loops, best of 3: 40.3 µs per loop


In [15]:
ijk = matmat_ijk(A,B)
ijk

array([[  4.,   5.,   6.,   7.],
       [ 12.,  17.,  22.,  27.],
       [ 20.,  29.,  38.,  47.]])

In [13]:
%timeit matmat_ikj(A,B)

The slowest run took 6.57 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 36.5 µs per loop


In [16]:
ikj = matmat_ikj(A,B)
ikj

array([[  4.,   5.,   6.,   7.],
       [ 12.,  17.,  22.,  27.],
       [ 20.,  29.,  38.,  47.]])

In [40]:
m, r = A.shape
r2, n = B.shape
C = np.zeros((m, n))

In [41]:
m,r,n

(3, 2, 4)

In [ ]:
dic = {
    
}

In [87]:
%timeit matmat_scalar(A, B, order = "ijk")

The slowest run took 5.25 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 41 µs per loop


In [67]:
%timeit matmat_scalar(A, B, order = "jik")

The slowest run took 4.34 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 41.3 µs per loop


In [68]:
%timeit matmat_scalar(A, B, order = "ikj")

The slowest run took 5.50 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 37 µs per loop


In [69]:
%timeit matmat_scalar(A, B, order = "jki")

The slowest run took 4.07 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 38.7 µs per loop


In [70]:
%timeit matmat_scalar(A, B, order = "kij")

10000 loops, best of 3: 36.6 µs per loop


In [74]:
%timeit matmat_scalar(A, B, order = "kji")

The slowest run took 5.84 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 38.1 µs per loop


In [88]:
%timeit matmat_scalar(A, B, order = "kjj")

Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Error
Erro

In [85]:
matmat_scalar(A, B, order = "kjj")

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
matmat_scalar(A, B, order = "ijk")

In [ ]:
for i,j in zip(pare,role):
    for

In [2]:
!pwd

/home/jovyan/work/Documents/GitHub/Matrix-Computations


In [5]:
import numpy as np

In [12]:
from gvpy.vecvec import copy

In [59]:
x = np.matrix( '1 2 3' )
y = np.matrix('0 -2 -3')

print( "x = " )
print( x )
print( "y = " )
print( y )

copy( x, y )
print( "y = " )
print( y )

assert np.array_equal(x,y), "error!"

x = 
[[1 2 3]]
y = 
[[ 0 -2 -3]]
y = 
[[1 2 3]]


In [65]:
z=np.copy(x)
print(z)

[[1 2 3]]


In [34]:
type(x)

numpy.matrixlib.defmatrix.matrix

In [35]:
x = np.array( [1, 2, 3] )
y = np.array([0, -2, -3])

print( "x = " )
print( x )
print( "y = " )
print( y )

copy( x, y )
print( "y = " )
print( y )

assert np.array_equal(x,y), "error!"

x = 
[1 2 3]
y = 
[ 0 -2 -3]


ValueError: not enough values to unpack (expected 2, got 1)

In [36]:
type(x)

numpy.ndarray

In [17]:
m_x, n_x = x.shape
m_y, n_y = y.shape

ValueError: not enough values to unpack (expected 2, got 1)

In [18]:
x = np.array( [1, 2, 3] )
y = np.array([0, -2, -3])

In [19]:
x.shape

(3,)

In [23]:
x.T

array([1, 2, 3])

In [24]:
x== x.T

array([ True,  True,  True], dtype=bool)

In [25]:
a = np.array([5,4])[np.newaxis]
print (a)
print (a.T)

[[5 4]]
[[5]
 [4]]


In [26]:
a.shape

(1, 2)

In [27]:
type(a)

numpy.ndarray

In [28]:
a = np.array([[5, 4]])
a.T

array([[5],
       [4]])

In [29]:
a

array([[5, 4]])

In [30]:
x

array([1, 2, 3])

In [31]:
x.T

array([1, 2, 3])

In [32]:
a.shape

(1, 2)

In [53]:
a=np.array([1,2,4])
print(a)
print(type(a))
print(a.shape)

[1 2 4]
<class 'numpy.ndarray'>
(3,)


In [54]:
b=a[:, None] *2
print(b)
print(type(b))
print(b.shape)

[[2]
 [4]
 [8]]
<class 'numpy.ndarray'>
(3, 1)


In [55]:
b

array([[2],
       [4],
       [8]])

In [56]:
a

array([1, 2, 4])

In [57]:
b=np.copy(a)

In [58]:
b

array([1, 2, 4])

In [75]:
x = np.arange(9).reshape(3,3,order="F")
y = np.array([[3],
             [2],
             [2]])
y

array([[3],
       [2],
       [2]])

In [76]:
np.dot(x,y)

array([[18],
       [25],
       [32]])

In [78]:
z = np.array([3,2,2])
z


array([3, 2, 2])

In [80]:
np.dot(x,2)

array([[ 0,  6, 12],
       [ 2,  8, 14],
       [ 4, 10, 16]])

In [81]:
x@y

array([[18],
       [25],
       [32]])

In [85]:
a = np.array([1, 2, 3, 4])
a.shape

(4,)

In [84]:
a.reshape(-1,1).shape

(4, 1)

In [86]:
a

array([1, 2, 3, 4])

In [92]:
b=a[:,None]
b

array([[1],
       [2],
       [3],
       [4]])

In [97]:
a[None,:]

array([[1, 2, 3, 4]])