# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Ch1,-P16" data-toc-modified-id="Ch1,-P16-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Ch1, P16</a></div><div class="lev1 toc-item"><a href="#Ch2,-P31" data-toc-modified-id="Ch2,-P31-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Ch2, P31</a></div><div class="lev1 toc-item"><a href="#Ch2,-P38" data-toc-modified-id="Ch2,-P38-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Ch2, P38</a></div><div class="lev1 toc-item"><a href="#Ch2,-P61,-P97" data-toc-modified-id="Ch2,-P61,-P97-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Ch2, P61, P97</a></div><div class="lev4 toc-item"><a href="#https://www.mathworks.com/help/matlab/ref/lu.html" data-toc-modified-id="https://www.mathworks.com/help/matlab/ref/lu.html-4001"><span class="toc-item-num">4.0.0.1&nbsp;&nbsp;</span><a href="https://www.mathworks.com/help/matlab/ref/lu.html" target="_blank">https://www.mathworks.com/help/matlab/ref/lu.html</a></a></div>

# Ch1, P16

In [2]:
v = [2 3 4]';
w = [1 1 1]';
u = 2 * v + 3 * w;
d = v' * w

d =  9


In [3]:
%%length
len_v1 = norm(v)
len_v2 = sqrt(v' * v)

len_v1 =  5.3852
len_v2 =  5.3852


In [10]:
%%cosine
cosine = v' * w / (norm(v) * norm(w))
angle = acos(cosine)

cosine =  0.96490
angle =  0.26573


# Ch2, P31

In [16]:
A = [1 -2;
     3 2  
    ];
    
b = [1 11]';

In [20]:
x = A\b

x =

   3
   1



In [19]:
%% Least squares solution to Ax=b
[xhat, p, e] = lsq(A, b)

xhat =

   3
   1

p =

    1
   11

e =

   0
   0



In [21]:
%% Particular solution of Ax=b
x = partic(A,b)

x =

   3
   1



In [22]:
%% solves the square system Ax = b
x = cramer(A, b)

x =

   3
   1



In [24]:
%% use the LU factorization computed by slu(A)
%% to solve the linear equation A*x = b
x = slv(A, b)

x =

   3   1



In [26]:
%%  uses the PA = LU factorization computed by splu
%%  to solve Ax = b.
x = splv(A, b)

Pivots in rows:
   1   2
x =

   3
   1



# Ch2, P38

In [5]:
A = [1 2 3;
     2 5 2;
     6 -3 1     
    ];
    
x = [0 0 2]';

In [6]:
b1 = A * x

b1 =

   6
   4
   2



In [7]:
%% Row at a time
b2 = [A(1,:) * x;
      A(2,:) * x;
      A(3,:) * x;
     ]

b2 =

   6
   4
   2



In [8]:
%% Column at a time    
b3 = A(:,1) * x(1) +  A(:,2) * x(2) + A(:,3) * x(3) 

b3 =

   6
   4
   2



In [9]:
%% operates on single entries at once, FORTRAN style
b4 =zeros(3,1);

for j = 1 : 3
  for i = 1 : 3
      b4(i) = b4(i) + A(i,j) * x(j)
  end
end

b4 =

   0
   0
   0

b4 =

   0
   0
   0

b4 =

   0
   0
   0

b4 =

   0
   0
   0

b4 =

   0
   0
   0

b4 =

   0
   0
   0

b4 =

   6
   0
   0

b4 =

   6
   4
   0

b4 =

   6
   4
   2



# Ch2, P61, P97

In [28]:
A = [1 2 1;
     3 8 1;
     0 4 1     
    ];
    
b = [2 12 2]';

#### https://www.mathworks.com/help/matlab/ref/lu.html

In [34]:
Y = lu(A)

Y =

   3.00000   8.00000   1.00000
   0.00000   4.00000   1.00000
   0.33333  -0.16667   0.83333



In [35]:
[L,U] = lu(A)

L =

   0.33333  -0.16667   1.00000
   1.00000   0.00000   0.00000
   0.00000   1.00000   0.00000

U =

   3.00000   8.00000   1.00000
   0.00000   4.00000   1.00000
   0.00000   0.00000   0.83333



In [37]:
[L,U,P] = lu(A)

L =

   1.00000   0.00000   0.00000
   0.00000   1.00000   0.00000
   0.33333  -0.16667   1.00000

U =

   3.00000   8.00000   1.00000
   0.00000   4.00000   1.00000
   0.00000   0.00000   0.83333

P =

Permutation Matrix

   0   1   0
   0   0   1
   1   0   0



In [38]:
[L,U,P,Q] = lu(A)

error: Invalid call to lu.  Correct usage is:

 -- Built-in Function: [L, U] = lu (A)
 -- Built-in Function: [L, U, P] = lu (A)
 -- Built-in Function: [L, U, P, Q] = lu (S)
 -- Built-in Function: [L, U, P, Q, R] = lu (S)
 -- Built-in Function: [...] = lu (S, THRES)
 -- Built-in Function: Y = lu (...)
 -- Built-in Function: [...] = lu (..., "vector")


Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [39]:
[L,U,P,Q,R] = lu(A)

error: Invalid call to lu.  Correct usage is:

 -- Built-in Function: [L, U] = lu (A)
 -- Built-in Function: [L, U, P] = lu (A)
 -- Built-in Function: [L, U, P, Q] = lu (S)
 -- Built-in Function: [L, U, P, Q, R] = lu (S)
 -- Built-in Function: [...] = lu (S, THRES)
 -- Built-in Function: Y = lu (...)
 -- Built-in Function: [...] = lu (..., "vector")


Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [36]:
%% LU factorization of a square matrix using *no row exchanges*
[L, U] = slu(A)

L =

   1   0   0
   3   1   0
   0   2   1

U =

   1   2   1
   0   2  -2
   0   0   5



In [33]:
%% Square PA=LU factorization *with row exchanges*
[P, L, U, sign] = splu(A)

P =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1

L =

   1   0   0
   3   1   0
   0   2   1

U =

   1   2   1
   0   2  -2
   0   0   5

sign =  1


In [4]:
a = 1;
b = 2;
c = 3;
n = 4;
T = tridiag(a, b, c, n)

T =

   2   3   0   0
   1   2   3   0
   0   1   2   3
   0   0   1   2



In [7]:
help tridiag

'tridiag' is a function from the file /home/jovyan/work/MIT_math/LA1806_MIT/mcode/Mfiles/tridiag.m

 tridiag  Tridiagonal matrix.
 T = tridiag(a, b, c, n) returns an n by n matrix that has 
 a, b, c as the subdiagonal, main diagonal, and superdiagonal 
 entries in the matrix.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [10]:
type  tridiag

tridiag is the user-defined function defined from: /home/jovyan/work/MIT_math/LA1806_MIT/mcode/Mfiles/tridiag.m

function T = tridiag(a, b, c, n)

% tridiag  Tridiagonal matrix.
% T = tridiag(a, b, c, n) returns an n by n matrix that has 
% a, b, c as the subdiagonal, main diagonal, and superdiagonal 
% entries in the matrix.

T = b*diag(ones(n,1)) + c*diag(ones(n-1,1),1) + a*diag(ones(n-1,1),-1);

